version: '3.9'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    entrypoint: >
      sh -c "
        /opt/bitnami/scripts/kafka/entrypoint.sh /run.sh &
        while ! kafka-topics.sh --bootstrap-server kafka:9092 --list; do sleep 1; done;
        kafka-topics.sh --create --topic my-topic --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1;
        sleep infinity;
      "

  kafka-backend:
    build: ./kafka-backend
    container_name: kafka-backend
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    networks:
      - kafka-net
    volumes:
      - ./kafka-backend:/app

  kafka-frontend:
    build: ./kafka-frontend
    container_name: kafka-frontend
    ports:
      - "3001:3000"
    depends_on:
      - kafka-backend
    networks:
      - kafka-net
    volumes:
      - ./kafka-frontend:/app

networks:
  kafka-net:
    driver: bridge
